# Generated by Django 5.2.7 on 2026-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
